# Generated by Django 4.1 on 2022-08-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='auto_file',
            new_name='autor_file',
        ),
    ]
